# This configuration file generates sample.report.md
file_summaries: true
file_changes_summary: true
test_coverage: true

report:
  Summary by GPT-4:
    _:
    Overview:
      _: What is the main goal of this PR?
      Suggestions: Any suggestions for improving the changes in this PR?
